import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import type { SceneOperations } from '../operations'

export const AGENT_GUIDE = [
  '# Pascal MCP Agent Guide',
  '',
  'You are editing Pascal architectural projects. Use MCP tools only; do not inspect the Pascal repository unless the user explicitly asks.',
  '',
  '## Standard Workflow',
  '',
  '1. Read this guide or call `get_capabilities` if available.',
  '2. If the user asks for a new project, call `create_project` first.',
  '3. For quick starts, call `create_house_from_brief`. For precise edits, build with semantic tools: `create_story_shell`, `create_room`, `add_door`, `add_window`, `furnish_room`, `create_roof`, `place_items`.',
  '4. Let semantic tools update the browser-visible draft. Call `save_scene` with `saveMode: "draft"` for autosave-style progress, or `saveMode: "checkpoint"` only for meaningful milestones.',
  '5. Call `validate_scene`, `verify_scene`, then `get_project_status`.',
  '6. Return the final `editorUrl` from tool output. Do not infer routes.',
  '',
  '## Important Concepts',
  '',
  '- A project is the browser-visible container.',
  '- A scene graph is the architectural model.',
  '- A draft is the browser-visible working model and may be overwritten many times.',
  '- A version/checkpoint is a meaningful saved model revision.',
  '- The browser editor opens the current draft when one exists, otherwise the published version.',
  '- Always return the `editorUrl`, not an internal API URL.',
  '',
  '## URLs',
  '',
  '- Use `editorUrl` returned by tools.',
  '- If a tool returns only an id, call `get_project_status` to get the browser URL.',
  '- Hosted editor URLs use `/editor/<projectId>`.',
  '',
  '## Scene Creation Rules',
  '',
  '- Prefer semantic tools over raw graph patches.',
  '- Do not hand-write node graphs unless no semantic tool exists.',
  '- When you do use `apply_patch` for bulk graph edits, batch-first is the default: one call containing all create/update/delete ops for the phase, in stable order so later ops can reference ids created earlier. A single call is atomic (all or nothing); do not loop one-op `apply_patch` calls.',
  '- For rooms, use `create_room` -> `add_door` -> `add_window` -> `furnish_room`.',
  '- Floors and ceilings are DERIVED from rooms, never authored. State intent — walls, separators and a zone with `spaceRole: "room"` — and the structure reconciler builds the floor plate and the ceiling for you. Creating a slab or ceiling carrying the derived markers (`boundary` / `autoFromWalls`), or reshaping or relinking one, is refused; deleting one records that opt-out on the zone instead. A room without a floor or ceiling is expressed on its zone (`hasFloor: false`, `hasCeiling: false`), and its floor height with `floor.elevation`.',
  '- Manual slabs remain valid for things that are not rooms: pools, platforms, stair decks, terraces at their own elevation.',
  '- `furnish_room` skips or nudges poses that block door clear zones or overlap other items; `verify_scene` and `check_collisions` report remaining issues.',
  '- Between adjacent rooms, prefer one shared wall (or only cut openings that line up). Leave ~0.65 m clear on both sides of each door; do not stack furniture footprints.',
  '- For complete homes, create exterior shell, interior rooms, openings, roof, furniture, then landscaping.',
  '- For doors/windows, use `t` or `position` from 0 to 1 along the wall unless a tool explicitly says otherwise.',
  '- X/Z are floor-plan axes and Y is vertical; dimensions are meters.',
  '- Use `create_roof` for roofs. A dedicated roof support level is valid and should not count as an occupied story.',
  '',
  '## Stairs',
  '',
  '- Call `measure_stair` before changing proportions. It is read-only and reports actual risers, walking-line going, arrival, uniformity, headroom and layout alternatives.',
  '- Use `fit_stair` for an explicit sizing or layout change. It applies uniform risers atomically; `fitRun: true` also adjusts flight runs or arc sweep. A straight, l or u layout replaces the flight chain. Turning strategy winder uses quarter-turn winders with configurable walking-line offset and division. Measure again after fitting.',
  '- Stair targets are design preferences in meters, not building-code certification: maxRiserHeight (default 0.18), minimumGoing (0.25), targetGoing (0.28), minimumHeadroom (2). Headroom checks cover modeled floors, ceilings and stair bodies; missing or unsupported obstacles still require inspection.',
  '',
  '## Looking and Starting Over',
  '',
  "- Call `view_scene` to see what you built from a viewpoint you pick (a compass side, a height, a street-level eye, an orthographic face, a photo's own camera) and compare it with the reference before fixing anything. It is a picture to compare, not a measurement. On a hosted server the person's open editor tab renders it; when the tab is hidden or closed the call is refused with the editor URL, so ask the person to bring it forward.",
  '- Call `clear_scene` only when the person asked to start over: it empties the project on purpose, keeping the site, the building and one level. Any other write that would leave the project empty is refused as `scene_wipe_blocked`, and nothing changes.',
  '',
  '## Custom Designs',
  '',
  '- A design (procedural item) is a JSON recipe: parameters, material slots and parts built from box, roundedBox, cylinder and ellipsoid shapes; version 2 adds extrude and revolve shapes, when/select options, and part trees with joints. Read `pascal://schema/design` for its JSON Schema, rules and a worked example.',
  '- Call `validate_design` after every edit until `valid` is true. It is the authority: it checks the rules JSON Schema cannot express, sweeps the parameter ranges, and measures bounds, parts, triangles, draw groups, datum contact and floating parts.',
  "- Then call `place_design` with a host that matches the design's mounting: a level (or slab or zone) or a design surface (`surfaceId`) for floor designs, a straight wall and `side` for wall-side designs, a ceiling for ceiling designs. It only creates; a refusal names what to change.",
  '',
  '## Required Final Checks',
  '',
  '- `save_scene` must succeed. Use `saveMode: "checkpoint"` before final handoff only if the user asked for a durable version.',
  '- `verify_scene.hasIssues` should be false; otherwise explain remaining issues.',
  '- `get_project_status.nodeCount` must be greater than 0 for a non-empty design.',
  '- Return `editorUrl` in the final user response.',
  '',
  '## If Something Looks Empty',
  '',
  '1. Call `get_project_status`.',
  '2. Compare `publishedVersion`, `latestVersion`, `browserVisibleVersion`, `nodeCount`, and `graphHash`.',
  '3. If the graph is non-empty but the browser appears empty, call `get_project_status` to re-bind the session, then `save_scene` with `saveMode: "draft"`.',
  '4. Re-run `verify_scene`.',
  '',
  '## Output Contract',
  '',
  'Final user response should include: project name, `editorUrl`, version, node/room summary, and any known limitations.',
].join('\n')

export function registerAgentGuide(server: McpServer, _bridge: SceneOperations): void {
  server.registerResource(
    'agent-guide',
    'pascal://agent-guide',
    {
      title: 'Pascal MCP agent guide',
      description:
        'Short MCP-first project creation, save/publish, validation, and output workflow for external agents.',
      mimeType: 'text/markdown',
    },
    async (uri) => ({
      contents: [
        {
          uri: uri.href,
          mimeType: 'text/markdown',
          text: AGENT_GUIDE,
        },
      ],
    }),
  )

  server.registerResource(
    'agent-guide-legacy',
    'pascal://agent/guide',
    {
      title: 'Pascal MCP agent guide',
      description: 'Legacy URI for the Pascal MCP agent guide. Prefer pascal://agent-guide.',
      mimeType: 'text/markdown',
    },
    async (uri) => ({
      contents: [
        {
          uri: uri.href,
          mimeType: 'text/markdown',
          text: AGENT_GUIDE,
        },
      ],
    }),
  )
}
